allow-lan: false
bind-address: 127.0.0.1
dns:
  ake-ip-range: 198.18.0.1/16
  default-nameserver:
  - 114.114.114.114
  - 119.29.29.29
  - 223.5.5.5
  enable: true
  enhanced-mode: redir-host
  fallback:
  - https://cloudflare-dns.com/dns-query
  - https://dns.google/dns-query
  - https://1.1.1.1/dns-query
  - tls://8.8.8.8:853
  fallback-filter:
    geoip: true
    ipcidr:
    - 240.0.0.0/4
  ipv6: false
  nameserver:
  - https://223.5.5.5/dns-query
  - https://223.6.6.6/dns-query
  - https://doh.pub/dns-query
  use-hosts: true
external-controller: 127.0.0.1:19090
log-level: warning
mixed-port: 9981
mode: rule
proxies:
- alterId: 2
  cipher: auto
  name: 香港綜合
  network: tcp
  port: 8388
  server: hk.tcpbbr.net
  tls: true
  type: vmess
  uuid: 2d981e22-b620-11ea-82ef-f23c9164ca5d
- name: HKBGP
  password: 2d981e22-b620-11ea-82ef-f23c9164ca5d
  port: 4700
  server: pccw.stunnel.vip
  tls: true
  type: http
  username: needmess@163.com
- alterId: 2
  cipher: auto
  name: 香港HKT
  network: ws
  port: 80
  server: hkt.comefromchinatown.com
  type: vmess
  uuid: 2d981e22-b620-11ea-82ef-f23c9164ca5d
  ws-headers:
    Host: broadcastlv.chat.bilibili.com
  ws-path: /
- alterId: 2
  cipher: auto
  name: 香港HKBN
  network: ws
  port: 80
  server: hkbn2.tcpbbr.net
  type: vmess
  uuid: 2d981e22-b620-11ea-82ef-f23c9164ca5d
  ws-headers:
    Host: broadcastlv.chat.bilibili.com
  ws-path: /
- alterId: 2
  cipher: auto
  name: 香港WTT
  network: ws
  port: 80
  server: wtt.comefromchinatown.com
  type: vmess
  uuid: 2d981e22-b620-11ea-82ef-f23c9164ca5d
  ws-headers:
    Host: images-eu.ssl-images-amazon.com
  ws-path: /
- alterId: 2
  cipher: auto
  name: 香港WTT4
  network: tcp
  port: 443
  server: wtt.tcpbbr.net
  tls: true
  type: vmess
  uuid: 2d981e22-b620-11ea-82ef-f23c9164ca5d
- alterId: 2
  cipher: auto
  name: 香港WTT2
  network: ws
  port: 80
  server: wtt2.comefromchinatown.com
  type: vmess
  uuid: 2d981e22-b620-11ea-82ef-f23c9164ca5d
  ws-headers:
    Host: images-eu.ssl-images-amazon.com
  ws-path: /
- alterId: 2
  cipher: auto
  name: 香港WTT3
  network: ws
  port: 80
  server: wtt3.comefromchinatown.com
  type: vmess
  uuid: 2d981e22-b620-11ea-82ef-f23c9164ca5d
  ws-headers:
    Host: images-eu.ssl-images-amazon.com
  ws-path: /
- alterId: 2
  cipher: auto
  name: HK游戏专线
  network: ws
  port: 15229
  server: game.tcpbbr.net
  type: vmess
  uuid: 2d981e22-b620-11ea-82ef-f23c9164ca5d
  ws-headers:
    Host: broadcastlv.chat.bilibili.com
  ws-path: /
- alterId: 2
  cipher: auto
  name: 美國-聖何塞
  network: ws
  port: 80
  server: us2.comefromchinatown.com
  type: vmess
  uuid: 2d981e22-b620-11ea-82ef-f23c9164ca5d
  ws-headers:
    Host: broadcastlv.chat.bilibili.com
  ws-path: /
- alterId: 2
  cipher: auto
  name: 美國綜合
  network: tcp
  port: 5329
  server: us.tcpbbr.net
  tls: true
  type: vmess
  uuid: 2d981e22-b620-11ea-82ef-f23c9164ca5d
- alterId: 2
  cipher: auto
  name: 美國-费利蒙
  network: ws
  port: 80
  server: us3.comefromchinatown.com
  type: vmess
  uuid: 2d981e22-b620-11ea-82ef-f23c9164ca5d
  ws-headers:
    Host: images-eu.ssl-images-amazon.com
  ws-path: /
- alterId: 2
  cipher: auto
  name: 台灣
  network: ws
  port: 80
  server: tw.tcpbbr.net
  type: vmess
  uuid: 2d981e22-b620-11ea-82ef-f23c9164ca5d
  ws-headers:
    Host: broadcastlv.chat.bilibili.com
  ws-path: /
- alterId: 2
  cipher: auto
  name: 日本
  network: ws
  port: 80
  server: jp.comefromchinatown.com
  type: vmess
  uuid: 2d981e22-b620-11ea-82ef-f23c9164ca5d
  ws-headers:
    Host: broadcastlv.chat.bilibili.com
  ws-path: /
- name: 台灣2
  password: 2d981e22-b620-11ea-82ef-f23c9164ca5d
  port: 10881
  server: tw.gotochinatown.net
  tls: true
  type: http
  username: needmess@163.com
- name: 法國
  password: 2d981e22-b620-11ea-82ef-f23c9164ca5d
  port: 10910
  server: fr.gotochinatown.net
  tls: true
  type: http
  username: needmess@163.com
- name: 英國
  password: 2d981e22-b620-11ea-82ef-f23c9164ca5d
  port: 10882
  server: uk.gotochinatown.net
  tls: true
  type: http
  username: needmess@163.com
- name: 俄羅斯
  password: 2d981e22-b620-11ea-82ef-f23c9164ca5d
  port: 10883
  server: ru.gotochinatown.net
  tls: true
  type: http
  username: needmess@163.com
proxy-groups:
- name: Ghelper
  proxies:
  - 全球智能
  - 香港智能
  - 香港綜合
  - HKBGP
  - 香港HKT
  - 香港HKBN
  - 香港WTT
  - 香港WTT4
  - 香港WTT2
  - 香港WTT3
  - HK游戏专线
  - 美國-聖何塞
  - 美國綜合
  - 美國-费利蒙
  - 台灣
  - 日本
  - 台灣2
  - 法國
  - 英國
  - 俄羅斯
  type: select
- interval: 300
  name: 全球智能
  proxies:
  - 香港綜合
  - 香港HKT
  - 香港HKBN
  - 香港WTT
  - 香港WTT4
  - 香港WTT2
  - 香港WTT3
  - 美國-聖何塞
  - 美國綜合
  - 美國-费利蒙
  - 台灣
  - 日本
  - 台灣2
  - 法國
  - 英國
  - 俄羅斯
  - HKBGP
  type: url-test
  url: http://www.gstatic.com/generate_204
- interval: 300
  name: 香港智能
  proxies:
  - 香港綜合
  - 香港HKT
  - 香港HKBN
  - 香港WTT
  - 香港WTT4
  - 香港WTT2
  - 香港WTT3
  - HKBGP
  type: url-test
  url: http://www.gstatic.com/generate_204
rules:
- DOMAIN-KEYWORD,google,Ghelper
- DOMAIN-KEYWORD,youtube,Ghelper
- DOMAIN-SUFFIX,ggpht.com,Ghelper
- DOMAIN-SUFFIX,gmail.com,Ghelper
- DOMAIN-SUFFIX,gvt2.com,Ghelper
- DOMAIN-SUFFIX,gvt3.com,Ghelper
- DOMAIN-SUFFIX,chrome.com,Ghelper
- DOMAIN-SUFFIX,wikipedia.org,Ghelper
- DOMAIN-SUFFIX,wikimedia.org,Ghelper
- DOMAIN-SUFFIX,appspot.com,Ghelper
- DOMAIN-SUFFIX,android.com,Ghelper
- DOMAIN-SUFFIX,github.com,Ghelper
- DOMAIN-SUFFIX,gitbook.com,Ghelper
- DOMAIN-SUFFIX,kaggle.com,Ghelper
- DOMAIN-SUFFIX,arxiv.org,Ghelper
- DOMAIN-SUFFIX,wiktionary.org,Ghelper
- DOMAIN-SUFFIX,blogger.com,Ghelper
- DOMAIN-SUFFIX,youtu.be,Ghelper
- DOMAIN-SUFFIX,ytimg.com,Ghelper
- IP-CIDR,192.168.0.0/16,DIRECT
- IP-CIDR,10.0.0.0/8,DIRECT
- IP-CIDR,172.16.0.0/12,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- IP-CIDR,100.64.0.0/10,DIRECT
- IP-CIDR6,::1/128,DIRECT
- IP-CIDR6,fc00::/7,DIRECT
- IP-CIDR6,fe80::/10,DIRECT
- IP-CIDR6,fd00::/8,DIRECT
- GEOIP,CN,DIRECT
- MATCH,Ghelper
